### ISSUE TITLE
Replace tokens in block title

### ISSUE THREAD

**Issue by kswan** [backdrop-contrib/token_block#9]
It would be nice to include tokens in the block titles. 

If this was added, it would be a simple work-around for this core feature request.
https://github.com/backdrop/backdrop-issues/issues/1860

**Comment by kswan** [comment]
PR submitted.

**Comment by argiepiano** [comment]
@kswan thank you for providing the PR. Looks good, but please see my comment there.

**Comment by argiepiano** [comment]
Pasting my response to your response here for visibility:

> I added the check_plain because the token_replace included html <p> tags

Block titles in Backdrop are not supposed to include markup. You can see this by creating a custom block with a title with markup. The markup will show as text. Same thing with node titles. If you create a node with a title that includes markup, it will show as text too.

So, your approach (effectively applying check_plain twice) changes the default behavior for of block titles. I don't know if this is problematic or not. I would like some feedback on this. 

EDIT:
One more thing I noticed. I created a node title with markup such `<i>Title</i>`. The doubled `check_plain()` is now outputting the image below - so effectively, using `check_plain` in your PR doesn't accomplish what you were trying (as I understood, you wanted the browser to interpret the markup). Perhaps I misunderstood your intent?


<img width="428" alt="Screen Shot 2024-05-17 at 7 03 20 AM" src="https://github.com/backdrop-contrib/token_block/assets/9938978/ebf41f0b-4368-41a3-8133-ffdad069abd9">

**Comment by argiepiano** [comment]
Im doing some testing now. There are issues with including tokens in the block titles. Basically, when you are using the layout UI, there is no node in the context. This creates the following warnings:

`
Warning: Undefined array key "node" in TokenBlock->getTitle() (line 23 of /Users/XXX/Sites/localhost/bdtesting/modules/token_block/token_block.block.inc).
Warning: Attempt to read property "data" on null in TokenBlock->getTitle() (line 23 of /Users/XXX/Sites/localhost/bdtesting/modules/token_block/token_block.block.inc).
`

So, IF this approach is safe (which I'm not yet sure, with the application of check_plain twice) then there has to be some logic to avoid trying to do a token replacement when using the layout UI.

**Comment by kswan** [comment]
Since the $data variable in getTitle is set using the same logic as getContent, wouldn't it have the same issue and warning?

**Comment by argiepiano** [comment]
> Since the $data variable in getTitle is set using the same logic as getContent, wouldn't it have the same issue and warning?

No, the warning only happens on the title field (and not in the content area) because the Layout UI actually renders that title when displaying the block structure in the layout UI. The block content is only rendered when the user access the layout during a front-end page request.  And at this point (when the layout is rendered "for real"), there is a node context available.

Didn't you see those warnings in your testing? (check the log).

**Comment by argiepiano** [comment]
@kswan thanks again for your work on this. I still think it's a good idea, once we fix the issues I mentioned. Would you be able to test my alternative PR? #11 

This PR avoids the warnings in the Layout UI, by outputting the raw token string (without trying to replace it, since the context is not available at this point). It also removes all markup, since block titles are not supposed to have any. It's now possible to use any token in the block title.

**Comment by kswan** [comment]
@argiepiano I tested your PR and it is working perfectly. 

I verified that the warnings were happening with my PR and are not with your PR.

Thank you for your help with this issue.

**Comment by argiepiano** [comment]
Thanks @kswan. Merged!
